export const id = "EVENT_COMPILE_PRESET_SFX";
export const name = "Compile Preset Sfx Data";
export const groups = ["Dynamic Sfx"];

export const autoLabel = (fetchArg, input) => {
  return `Compile Preset Sfx Data (${input.data_symbol || "?"})`;
};

export const fields = [
  {
    label:
      "Compiles a preset (base sound + pitch + length) into ROM data at build time. Play it with 'Play Compiled Preset Sfx' using the same data symbol. This event emits no runtime code - it just needs to exist in a script that gets compiled.",
  },
  {
    key: "data_symbol",
    label: "Data Symbol",
    description:
      "Unique C symbol name for this preset (letters, digits, underscores)",
    type: "text",
    defaultValue: "my_preset_sfx",
  },
  {
    key: "baseSymbol",
    label: "Base Sfx Data Symbol",
    description:
      "Data symbol of a sound created with 'Compile Base Sfx Data'",
    type: "text",
    defaultValue: "my_base_sfx",
  },
  {
    key: "pitch",
    label: "Pitch (0-255)",
    description:
      "Added to the frequency of every note. 0 = the base sound as-is; higher values raise the pitch (also shifts the noise channel).",
    type: "number",
    min: 0,
    max: 255,
    width: "50%",
    defaultValue: 0,
  },
  {
    key: "length",
    label: "Length (0-255)",
    description:
      "Note duration factor. 128 = normal speed, 0 = double speed (half length), 255 = about 1.5x longer.",
    type: "number",
    min: 0,
    max: 255,
    width: "50%",
    defaultValue: 128,
  },
];

const clamp = (v, min, max) => Math.min(max, Math.max(min, Number(v) || 0));

export const compile = (input, helpers) => {
  const { writeAsset, _getAvailableSymbol, _addComment } = helpers;

  const symbol = _getAvailableSymbol(input.data_symbol || "my_preset_sfx");
  const baseSymbol = input.baseSymbol || "my_base_sfx";
  const pitch = clamp(input.pitch, 0, 255);
  const length = clamp(input.length, 0, 255);

  _addComment(`Compile Preset Sfx Data: ${symbol} (build-time only)`);

  writeAsset(
    `${symbol}.c`,
    `#pragma bank 255

// Generated by the Dynamic Sfx plugin "Compile Preset Sfx Data" event.

#include "data/${symbol}.h"
#include "data/${baseSymbol}.h"

BANKREF(${symbol})

const dynsfx_preset_def_t ${symbol} = {
    TO_FAR_PTR_T(${baseSymbol}),
    ${pitch},
    ${length},
};
`
  );

  writeAsset(
    `${symbol}.h`,
    `#ifndef __${symbol}_INCLUDE__
#define __${symbol}_INCLUDE__

#include "dynamic_sfx_player.h"

BANKREF_EXTERN(${symbol})
extern const dynsfx_preset_def_t ${symbol};

#endif
`
  );
};
